version: "3.8"
services:
  servidor:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/ubuntu/jls-Dockerfile
      args: 
        - CONTEXT=${CONTEXTO}
        - TZ=${TZ}
        - PROYECTO=${PROYECTO}
    image: ${AUTOR}/jls-ubuntubase
    container_name: miservidor
    hostname: ${HOSTNAME}
    env_file:
      - ./.env
    environment:
      - USUARIO=${USUARIO}
      - PASSWORD=${PASSWD}
    volumes:
      - ./logs:/root/logs
    networks:
      netcaronte:
        ipv4_address: 172.120.10.2

networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: 172.120.10.0/24